import type { Metadata } from "next";
import ClientLayout from "./clientlayout"; // ye client component hoga

export const metadata: Metadata = {
  title: "Talha Work",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head />
      <body>
        {/* ClientLayout ke andar loader aur navbar h */}
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
